name: Deploy to AWS

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Download Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./bidflare-backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bidflare-backend:latest

      # 4. Build & Push Frontend (Injecting the IP)
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./bidflare-frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bidflare-frontend:latest
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_URL }}/api
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51SS79pGdFGF85Pk32GrY1S9aKcQOrevqWfsCEhZW9iq81wRraohraf5lSm70DmZCb8lwVpuv8fgcmlNJZhhvYlC600RbHF0z13

      # 5. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/

            # Create .env file on server if it doesn't exist (Optional safety)
            # Note: Ideally, you manually placed your full .env file here already.

            # Pull the NEW images
            docker compose pull

            # Restart containers with the new code
            docker compose up -d

            # Clean up old images to save space
            docker system prune -f
